
### This file is automatically generated, do not edit it   
### This file Recorded each device corresponding to the    
### CoocaaOS customization mk,                             
### As well as the corresponding product configuration     


full_sky828_5s02 = 5S02_15U
full_sky938_5s07 = 5S07_A2

